---
title: "MASH"
author: "Emily Bellis"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load distance matrices
```{r}
setwd('/Users/emilywork/Documents/GitHub/StrigaWGS/')
library(tidyverse)

k31 <- read.table("k31.mash.out", header=F)
k31 <- k31 %>% select(1:3)
colnames(k31) <- c("S1","S2","dist")
k31 <- as.matrix(k31 %>% pivot_wider(names_from = S2, values_from = dist) %>%
                   column_to_rownames(var="S1")
)

k21 <- read.table("k21.mash.out", header=F)
k21 <- k21 %>% select(1:3)
colnames(k21) <- c("S1","S2","dist")
k21 <- as.matrix(k21 %>% pivot_wider(names_from = S2, values_from = dist) %>%
                   column_to_rownames(var="S1")
)
```

## Visualize PCoA for k21
```{r}
library(ape)
k21.dist <- as.dist(k21)
k21.pcoa <- ape::pcoa(k21.dist, correction="none", rn=NULL)

tmp <- cbind.data.frame("Axis"=1:68,"Cum_br_stick"= k21.pcoa$values$Cumul_br_stick, "Broken_stick"=k21.pcoa$values$Broken_stick)
ggplot(tmp, aes(x=Axis, y=Cum_br_stick)) + geom_line() + geom_point()

tmp2 <- cbind.data.frame("SampleID"=rownames(k21.pcoa$vectors), "Axis1"=k21.pcoa$vectors[,1], "Axis2"=k21.pcoa$vectors[,2])

# get metadata for samples
meta <- read.csv('Striga_GPS.csv', header=T)
meta <- meta %>% select(SampleID, Site, Host)
tmp2 <- inner_join(meta, tmp2)

ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + geom_point()

tmp2$Site <- as.factor(str_replace(tmp2$Site, "2","") %>% str_trim())
ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + 
  geom_point(size=2, alpha=0.8) + 
  theme_classic()

# subset to just the two well-sampled locations
tmp3 <- tmp2 %>% filter(Site == "HomaBay" | Site=="Kisii")
ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + 
  geom_point(size=2, alpha=0.8) + 
  theme_classic() +
  xlab(paste0("Axis1(",round(tmp$Broken_stick[1]*100,2),"%)")) +
  ylab(paste0("Axis2(",round(tmp$Broken_stick[2]*100,2),"%)")) +
  ggtitle("k21")
```


## Visualize PCoA for k31
```{r}
library(ape)
k31.dist <- as.dist(k31)
k31.pcoa <- ape::pcoa(k31.dist, correction="none", rn=NULL)

tmp <- cbind.data.frame("Axis"=1:68,"Cum_br_stick"= k31.pcoa$values$Cumul_br_stick, "Broken_stick"=k31.pcoa$values$Broken_stick)
ggplot(tmp, aes(x=Axis, y=Cum_br_stick)) + geom_line() + geom_point()

tmp2 <- cbind.data.frame("SampleID"=rownames(k31.pcoa$vectors), "Axis1"=k31.pcoa$vectors[,1], "Axis2"=k31.pcoa$vectors[,2])

# get metadata for samples
meta <- read.csv('Striga_GPS.csv', header=T)
meta <- meta %>% select(SampleID, Site, Host)
tmp2 <- inner_join(meta, tmp2)

ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + geom_point()

tmp2$Site <- as.factor(str_replace(tmp2$Site, "2","") %>% str_trim())
ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + 
  geom_point(size=2, alpha=0.8) + 
  theme_classic()

# subset to just the two well-sampled locations
tmp3 <- tmp2 %>% filter(Site == "HomaBay" | Site=="Kisii")
ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + 
  geom_point(size=2, alpha=0.8) + 
  theme_classic() +
  xlab(paste0("Axis1(",round(tmp$Broken_stick[1]*100,2),"%)")) +
  ylab(paste0("Axis2(",round(tmp$Broken_stick[2]*100,2),"%)")) +
  ggtitle("k31")
```

