---
title: "MASH"
author: "Emily Bellis"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load distance matrices
```{r}
#setwd("/Users/ebellis/Documents/GitHub/StrigaWGS/")
library(tidyverse)
library(ape)
library(jcolors)

k31 <- read.table("k31.mash.out", header=F)
k31 <- k31 %>% select(1:3)
colnames(k31) <- c("S1","S2","dist")
```

## Run PCoA for each dataset
```{r}
meta <- read.csv('Fig1_mapxPCoA/Striga_GPS.csv', header=T)
meta$Site <- as.factor(str_replace(meta$Site, "2","") %>% str_trim())
meta <- meta %>% filter(SampleID %in% unique(k31$S1))

# function to run PCoA and return clean df
runPCoA <- function(part, meta) {
  # filter metadata 
  if(part == "A") {
      meta_sub <- meta
  } else if (part == "B") {
      meta_sub <- filter(meta, Site != "Kisii") %>% 
        filter(Site != "Homa Bay")
      meta_subkh <- filter(meta, 
                         SampleID =="SH130"| SampleID =="SH134"|
                         SampleID =="SH138"| SampleID =="SH139"|
                         SampleID =="SH146"| SampleID =="SH124"|
                         SampleID =="SH117"| SampleID =="SH113"|
                         SampleID =="SH111"|SampleID =="SH104")
      meta_sub <- rbind(meta_sub, meta_subkh)
  } else if (part == "C") {
      meta_sub <- filter(meta, Site == "Kisii")
  } else if (part == "D") {
      meta_sub <- filter(meta, Site == "Homa Bay")
  }
  
  # create distance matrix
  k31_flt <- k31 %>% filter(S1 %in% meta_sub$SampleID) %>%
    filter(S2 %in% meta_sub$SampleID)

  k31_flt <- as.matrix(k31_flt %>% 
                       pivot_wider(names_from = S2, 
                                   values_from = dist) %>% 
                       column_to_rownames(var="S1"))
  k31.dist <- as.dist(k31_flt)
  
  # run PCoA
  k31.pcoa <- ape::pcoa(k31.dist, correction="none", rn=NULL)

  # create df of results
  df <- cbind.data.frame("SampleID"=rownames(k31.pcoa$vectors),
                         "Axis1"=k31.pcoa$vectors[,1],
                         "Axis2"=k31.pcoa$vectors[,2])
  # add metadata
  #meta <- read.csv('Striga_GPS.csv', header=T)
  #meta$Site <- as.factor(str_replace(meta$Site, "2","") %>% str_trim())
  tmp <- meta %>% select(SampleID, Site, Host)
  df <- inner_join(tmp, df)
  return(df)
}

# loop through each figure part to create final df
FigParts = c("A","B","C","D")
for (i in 1:4){
  df <- runPCoA(FigParts[i], meta)
  df$part <- FigParts[i]
  if(i > 1){
    df <- rbind.data.frame(df_old, df)
    df_old <- df
  } else {
    df_old <- df
  }
}
```

## Visualize PCoA
```{r}
df$Site <- as.factor(df$Site)
df$Host <- as.factor(df$Host)

p <- ggplot(df, aes(x=Axis1, y=Axis2, col=Site, fill=Site, shape=Host)) + 
  geom_point(alpha = 0.6, size = 2.5) + 
  theme_classic() +
  scale_colour_manual(values=paste0(jcolors(palette="pal5"))) +
  facet_wrap(.~part) + 
  scale_shape_manual(values = c(16, 2, 15, 3)) 

pdf(file="Fig2.pdf",width=5,height=5)
p
dev.off()
```
