---
title: "MASH"
author: "Emily Bellis"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load distance matrices
```{r}
#setwd("/Users/ebellis/Documents/GitHub/StrigaWGS/")
library(tidyverse)

k31 <- read.table("k31.mash.out", header=F)
k31 <- k31 %>% select(1:3)
colnames(k31) <- c("S1","S2","dist")
```

## Load metadata and create subsets
```{r}
meta <- read.csv('Striga_GPS.csv', header=T)
meta$Site <- as.factor(str_replace(meta$Site, "2","") %>% str_trim())
meta <- meta %>% filter(SampleID %in% unique(k31$S1))

list5per <- filter(meta, Site == "Kisii"| Site == "Homa Bay")
list5per <- filter(meta, Site == "Homa Bay")

k31_flt <- k31 %>% filter(S1 %in% list5per$SampleID) %>%
  filter(S2 %in% list5per$SampleID)

k31_flt <- as.matrix(k31_flt %>% 
                       pivot_wider(names_from = S2, values_from = dist) %>% 
                       column_to_rownames(var="S1")
)
```

## Visualize PCoA for k21
```{r}
library(ape)
k31.dist <- as.dist(k31_flt)
k31.pcoa <- ape::pcoa(k31.dist, correction="none", rn=NULL)

tmp <- cbind.data.frame("Axis"=1:(nrow(list5per)-1),"Cum_br_stick"= k31.pcoa$values$Cumul_br_stick, "Broken_stick"=k31.pcoa$values$Broken_stick)
#ggplot(tmp, aes(x=Axis, y=Cum_br_stick)) + geom_line() + geom_point()

tmp2 <- cbind.data.frame("SampleID"=rownames(k31.pcoa$vectors), "Axis1"=k31.pcoa$vectors[,1], "Axis2"=k31.pcoa$vectors[,2])

# get metadata for samples
meta <- read.csv('Striga_GPS.csv', header=T)
meta$Site <- as.factor(str_replace(meta$Site, "2","") %>% str_trim())
meta <- meta %>% select(SampleID, Site, Host)
tmp2 <- inner_join(meta, tmp2)

p <- ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Host, pch=Host)) + 
  geom_point(size=2.5) + 
  theme_classic() +
  xlab(paste0("Axis1(",round(tmp$Broken_stick[1],3)*100,"%)")) +
  ylab(paste0("Axis2(",round(tmp$Broken_stick[2],3)*100,"%)")) +
  scale_color_manual(values=c("#C5D86D","#17377A"))

pdf(file="Fig1_C.pdf",width=3,height=3)
p + theme(legend.position = "top")
dev.off()
```
