---
title: "IBD"
author: "eb"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load genetic data as distance matrix
```{r}
library(adegenet)
library(tidyverse)

k31 <- read.table("../Fig1_mapxPCoA/k31.mash.out", header=F)
k31 <- k31 %>% dplyr::select(1:3)
colnames(k31) <- c("S1","S2","dist")
k31$S1 <- as.factor(k31$S1)
k31$S2 <- as.factor(k31$S2)
k31_df <- k31
k31 <- as.matrix(k31 %>% 
                   pivot_wider(names_from = S2, 
                               values_from = dist) %>% 
                   column_to_rownames(var="S1"))
k31.dist <- as.dist(k31)
```

## load geographic data as distance matrix
```{r}
library(geodist)
getwd()
modern <- read.csv("../Fig1_mapxPCoA/Striga_GPS.csv", header=T)
modern <- modern %>% dplyr::select(SampleID, Lat, Lon)
modern <- modern %>% filter(SampleID %in% unique(rownames(k31)))

geomat <- geodist(modern, sequential = F, measure = "geodesic")/1000
rownames(geomat) <- modern$SampleID
colnames(geomat) <- modern$SampleID
geomat_mat <- geomat
geomat <- as.dist(geomat)
```

## run mantel test
```{r}
ibd <- mantel.randtest(k31.dist,geomat)
plot(ibd) # significant IBD, p=0.003
```

## dbMEM analysis
```{r}
library(adespatial)

dbmem(k31.dist, geomat)
```


## is this due to clines or clusters?
```{r}
library(MASS)
dens <- kde2d(geomat,k31.dist, n=300)
myPal <- colorRampPalette(c("white","blue","gold", "orange", "red"))

pdf("Fig1D_IBD.pdf", width = 3, height=3)
plot(geomat,k31.dist, pch=20,cex=.5, xlab="Distance (km)", alpha = 0.5, ylab="k-mer distance")
image(dens, col=transp(myPal(300),.7), add=TRUE)
abline(lm(k31.dist ~ geomat))
dev.off()
```

## what about within population k-mer diversity?
```{r}
k31_df$Same_host <- 'N'
k31_df$km <- 'N'
modern <- read.csv("../Fig1/Striga_GPS.csv", header=T)

for (i in 1:nrow(k31_df)) {
  if (modern[modern$SampleID == k31_df$S1[i],3] ==
    modern[modern$SampleID == k31_df$S2[i],3]) {
    k31_df$Same_host[i] <- 'Y'
  }
  k31_df$km[i] <- geomat_mat[k31_df$S1[i],k31_df$S2[i]]
}

k31_df$km <- as.numeric(k31_df$km)

p <- ggplot(k31_df, aes(x = km, y = dist)) +
  geom_point(alpha = 0.1) +
  ylim(c(0.02, 0.030)) +
  geom_smooth(method='lm', se = F, lty = 2) +
  theme_classic() +
  xlab("Geographic distance (km)") +
  ylab("Genetic distance") +
  facet_grid(.~Same_host)# these are the self comparisons
mod1 <- lm(dist ~ km, data = k31_df)

pdf("geo_v_gen.pdf", width = 3, height = 1.75)
p
dev.off()
```

## range of values within vs. between populations?
```{r}
same_pop <- subset(k31_df, km == 0 & S1 != S2)
diff_pop <- subset(k31_df, km >= 100 & S1 != S2)

quantile(same_pop$dist)
quantile(diff_pop$dist)
```

