---
title: "IBD"
author: "eb"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load genetic data as distance matrix
```{r}
library(adegenet)

k21 <- read.table("k21.mash.out", header=F)
k21 <- k21 %>% select(1:3)
colnames(k21) <- c("S1","S2","dist")
k21 <- as.matrix(k21 %>% 
                       pivot_wider(names_from = S2, values_from = dist) %>% 
                       column_to_rownames(var="S1"))
k21.dist <- as.dist(k21)
```

## load geographic data as distance matrix
```{r}
library(geodist)
modern <- read.csv("Striga_GPS.csv", header=T)
modern <- modern %>% dplyr::select(SampleID, Lat, Lon)
modern <- modern %>% filter(SampleID %in% unique(k21$S1))

geomat <- geodist(modern, sequential = F, measure = "geodesic")/1000
rownames(geomat) <- modern$SampleID
colnames(geomat) <- modern$SampleID
geomat <- as.dist(geomat)
```

# run mantel test
```{r}
ibd <- mantel.randtest(k21.dist,geomat)
plot(ibd) # significant IBD, p=0.003
```

# is this due to clines or clusters?
```{r}
library(MASS)
dens <- kde2d(geomat,k21.dist, n=300)
myPal <- colorRampPalette(c("white","blue","gold", "orange", "red"))

pdf("Fig1D_IBD.pdf", width = 3, height=3)
plot(geomat,k21.dist, pch=20,cex=.5, xlab="Distance (km)", ylab="k-mer distance")
image(dens, col=transp(myPal(300),.7), add=TRUE)
abline(lm(k21.dist ~ geomat))
dev.off()
```

