---
title: "MASH"
author: "Emily Bellis"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load distance matrices
```{r}
#setwd("/Users/ebellis/Documents/GitHub/StrigaWGS/")
library(tidyverse)

k21 <- read.table("k21.mash.out", header=F)
k21 <- k21 %>% select(1:3)
colnames(k21) <- c("S1","S2","dist")
```

## Load metadata and create subsets
```{r}
meta <- read.csv('Striga_GPS.csv', header=T)
meta$Site <- as.factor(str_replace(meta$Site, "2","") %>% str_trim())
meta <- meta %>% filter(SampleID %in% unique(k21$S1))

list5per <- filter(meta, Site != "Kisii" & Site != "HomaBay")$SampleID
list5perkh <- filter(meta, SampleID =="SH130" | SampleID =="SH134"|SampleID =="SH138"| SampleID =="SH139"|SampleID =="SH146"|SampleID =="SH124"|SampleID =="SH117"|SampleID =="SH113"|SampleID =="SH111"|SampleID =="SH104")$SampleID
#k21[c(list5per,list5perkh),]
#list5 <- c(list5per,list5perkh)

#k21 <- as.matrix(k21 %>% pivot_wider(names_from = S2, values_from = dist) %>%
                   column_to_rownames(var="S1")
)
```

## Visualize PCoA for k21
```{r}
library(ape)
k21.dist <- as.dist(k21)
k21.pcoa <- ape::pcoa(k21.dist, correction="none", rn=NULL)

tmp <- cbind.data.frame("Axis"=1:68,"Cum_br_stick"= k21.pcoa$values$Cumul_br_stick, "Broken_stick"=k21.pcoa$values$Broken_stick)
ggplot(tmp, aes(x=Axis, y=Cum_br_stick)) + geom_line() + geom_point()

tmp2 <- cbind.data.frame("SampleID"=rownames(k21.pcoa$vectors), "Axis1"=k21.pcoa$vectors[,1], "Axis2"=k21.pcoa$vectors[,2])

# get metadata for samples
meta <- read.csv('Striga_GPS.csv', header=T)
meta <- meta %>% select(SampleID, Site, Host)
tmp2 <- inner_join(meta, tmp2)

ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + geom_point()

ggplot(tmp2, aes(x=Axis1, y=Axis2, col=Site, pch=Host)) + 
  geom_point(size=2, alpha=0.8) + 
  theme_classic()
```
